#!/bin/bash
set -e

MAIL_DOMAIN="hyvechain.com"
MAIL_HOSTNAME="mail.hyvechain.com"
MAIL_API_HOSTNAME="mail-api.hyvechain.com"

# Server IP
SERVER_IP="68.168.218.138"
echo "=== HyveMail Setup for ${MAIL_DOMAIN} ==="
echo "    Server IP: ${SERVER_IP}"
echo "    Hostname:  ${MAIL_HOSTNAME}"
echo ""

# ========================================
# STEP 1: Install Dependencies
# ========================================
echo "=== Installing required packages ==="
apt-get update -qq
apt-get install -y postfix dovecot-imapd dovecot-lmtpd opendkim opendkim-tools \
  certbot mailutils > /dev/null 2>&1
echo "Packages installed"

# ========================================
# STEP 2: OpenDKIM (CRITICAL for outbound delivery)
# ========================================
echo "=== Setting up OpenDKIM ==="

mkdir -p /etc/opendkim/keys/${MAIL_DOMAIN}

# Generate DKIM keys if they don't exist
if [ ! -f /etc/opendkim/keys/${MAIL_DOMAIN}/mail.private ]; then
  opendkim-genkey -D /etc/opendkim/keys/${MAIL_DOMAIN}/ -d ${MAIL_DOMAIN} -s mail -b 2048
  echo "DKIM keys generated"
else
  echo "DKIM keys already exist"
fi

chown -R opendkim:opendkim /etc/opendkim
chmod 600 /etc/opendkim/keys/${MAIL_DOMAIN}/mail.private

# Configure OpenDKIM
cat > /etc/opendkim.conf << 'DKIMCONF'
AutoRestart             Yes
AutoRestartRate         10/1h
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes
Canonicalization        relaxed/simple
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
Mode                    sv
PidFile                 /run/opendkim/opendkim.pid
SignatureAlgorithm      rsa-sha256
UserID                  opendkim:opendkim
Socket                  local:/var/spool/postfix/opendkim/opendkim.sock
DKIMCONF

# Signing table - which domains to sign
cat > /etc/opendkim/SigningTable << EOF
*@${MAIL_DOMAIN}  mail._domainkey.${MAIL_DOMAIN}
EOF

# Key table - where to find the keys
cat > /etc/opendkim/KeyTable << EOF
mail._domainkey.${MAIL_DOMAIN}  ${MAIL_DOMAIN}:mail:/etc/opendkim/keys/${MAIL_DOMAIN}/mail.private
EOF

# Trusted hosts
cat > /etc/opendkim/TrustedHosts << EOF
127.0.0.1
localhost
${MAIL_DOMAIN}
*.${MAIL_DOMAIN}
EOF

# Create socket directory inside Postfix chroot
mkdir -p /var/spool/postfix/opendkim
chown opendkim:postfix /var/spool/postfix/opendkim
chmod 750 /var/spool/postfix/opendkim

# Add postfix to opendkim group
usermod -a -G opendkim postfix

echo "OpenDKIM configured"

# Print the DKIM DNS record
echo ""
echo "=============================================="
echo "  IMPORTANT: Add this DKIM DNS TXT record!"
echo "=============================================="
echo "  Name: mail._domainkey.${MAIL_DOMAIN}"
echo "  Value:"
cat /etc/opendkim/keys/${MAIL_DOMAIN}/mail.txt
echo "=============================================="
echo ""

# ========================================
# STEP 3: Postfix main.cf (CRITICAL - was missing!)
# ========================================
echo "=== Configuring Postfix main.cf ==="

cat > /etc/postfix/main.cf << MAINCF
# HyveMail Postfix configuration
# Generated by setup-mail.sh

# Basic settings
smtpd_banner = \$myhostname ESMTP
biff = no
append_dot_mydomain = no
readme_directory = no
compatibility_level = 3.6

# Hostname and domain
myhostname = ${MAIL_HOSTNAME}
mydomain = ${MAIL_DOMAIN}
myorigin = \$mydomain
mydestination = localhost
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128

# Virtual mailbox configuration
virtual_mailbox_domains = ${MAIL_DOMAIN}
virtual_mailbox_base = /var/vmail
virtual_mailbox_maps = hash:/etc/postfix/vmailbox
virtual_alias_maps = hash:/etc/postfix/virtual
virtual_minimum_uid = 100
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
virtual_transport = lmtp:unix:private/dovecot-lmtp

# TLS parameters (inbound)
smtpd_tls_cert_file = /etc/letsencrypt/live/${MAIL_API_HOSTNAME}/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/${MAIL_API_HOSTNAME}/privkey.pem
smtpd_tls_security_level = may
smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtpd_tls_mandatory_ciphers = medium
smtpd_tls_session_cache_database = btree:\${data_directory}/smtpd_scache

# TLS parameters (outbound - for sending to external servers)
smtp_tls_security_level = may
smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_mandatory_ciphers = medium
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_loglevel = 1

# SASL authentication (via Dovecot)
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain = \$myhostname

# Recipient restrictions
smtpd_recipient_restrictions =
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination

# DKIM Milter
milter_default_action = accept
milter_protocol = 6
smtpd_milters = local:opendkim/opendkim.sock
non_smtpd_milters = \$smtpd_milters

# Message size limit (25MB)
message_size_limit = 26214400
mailbox_size_limit = 0

# Queue settings for outbound delivery
smtp_connect_timeout = 30s
smtp_helo_timeout = 30s
maximal_queue_lifetime = 5d
bounce_queue_lifetime = 5d

# Disable local delivery
local_transport = virtual
MAINCF

echo "Postfix main.cf written"

# ========================================
# STEP 4: Virtual mailbox maps
# ========================================
echo "=== Setting up Postfix virtual mailbox maps ==="

# Create virtual mailbox map
cat > /etc/postfix/vmailbox << 'EOF'
postmaster@hyvechain.com hyvechain.com/postmaster/
EOF

# Create virtual alias map
cat > /etc/postfix/virtual << 'EOF'
postmaster@hyvechain.com postmaster@hyvechain.com
abuse@hyvechain.com postmaster@hyvechain.com
EOF

postmap /etc/postfix/vmailbox
postmap /etc/postfix/virtual
echo "Postfix maps created"

# ========================================
# STEP 5: Postfix master.cf
# ========================================
echo "=== Configuring Postfix master.cf ==="

# Enable submission port (587) in master.cf
cat > /etc/postfix/master.cf << 'MASTER'
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
# ==========================================================================
smtp      inet  n       -       y       -       -       smtpd
submission inet n       -       y       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_tls_auth_only=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
smtps     inet  n       -       y       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
  -o syslog_name=postfix/$service_name
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
MASTER
echo "master.cf written"

echo "=== Configuring Dovecot ==="

# Main dovecot config
cat > /etc/dovecot/dovecot.conf << 'DOVECOTCONF'
protocols = imap lmtp
listen = *, ::
dict {
}
!include conf.d/*.conf
DOVECOTCONF

# Mail location - Maildir format
cat > /etc/dovecot/conf.d/10-mail.conf << 'MAILCONF'
mail_location = maildir:/var/vmail/%d/%n/Maildir
mail_privileged_group = vmail
mail_uid = 5000
mail_gid = 5000
first_valid_uid = 5000
last_valid_uid = 5000

namespace inbox {
  inbox = yes
  separator = /

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Starred {
    auto = subscribe
  }
}
MAILCONF

# Authentication - passwd-file for virtual users
cat > /etc/dovecot/conf.d/10-auth.conf << 'AUTHCONF'
disable_plaintext_auth = yes
auth_mechanisms = plain login

passdb {
  driver = passwd-file
  args = scheme=BLF-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=5000 gid=5000 home=/var/vmail/%d/%n
}
AUTHCONF

# SSL config
cat > /etc/dovecot/conf.d/10-ssl.conf << 'SSLCONF'
ssl = required
ssl_cert = </etc/letsencrypt/live/mail-api.hyvechain.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/mail-api.hyvechain.com/privkey.pem
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
SSLCONF

# Master config - LMTP socket for Postfix, auth socket for Postfix SASL
cat > /etc/dovecot/conf.d/10-master.conf << 'MASTERCONF'
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service imap {
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0660
    user = vmail
    group = vmail
  }
}

service auth-worker {
  user = vmail
}
MASTERCONF

# Logging
cat > /etc/dovecot/conf.d/10-logging.conf << 'LOGCONF'
log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot-info.log
LOGCONF

# Create empty users file
touch /etc/dovecot/users
chown root:dovecot /etc/dovecot/users
chmod 640 /etc/dovecot/users

echo "Dovecot configured"

echo "=== Creating postmaster account ==="
# Create a postmaster password (use doveadm to hash)
POSTMASTER_PASS=$(openssl rand -base64 16)
POSTMASTER_HASH=$(doveadm pw -s BLF-CRYPT -p "$POSTMASTER_PASS")
echo "postmaster@hyvechain.com:${POSTMASTER_HASH}" > /etc/dovecot/users

# Create postmaster maildir
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/{cur,new,tmp}
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/.Sent/{cur,new,tmp}
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/.Drafts/{cur,new,tmp}
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/.Trash/{cur,new,tmp}
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/.Spam/{cur,new,tmp}
mkdir -p /var/vmail/hyvechain.com/postmaster/Maildir/.Starred/{cur,new,tmp}
chown -R vmail:vmail /var/vmail/hyvechain.com

echo "Postmaster password: $POSTMASTER_PASS"
echo "(Save this somewhere safe!)"

# ========================================
# STEP 8: Set up SPF helper (policyd-spf)
# ========================================
echo "=== Verifying SPF configuration ==="
echo "Ensure these DNS records are set:"
echo ""
echo "  TXT  @        v=spf1 mx a:${MAIL_HOSTNAME} ip4:${SERVER_IP} -all"
echo "  TXT  _dmarc   v=DMARC1; p=quarantine; rua=mailto:postmaster@${MAIL_DOMAIN}; fo=1"
echo "  MX   @        ${MAIL_HOSTNAME} (priority 10)"
echo "  A    mail     ${SERVER_IP}"
echo "  PTR  ${SERVER_IP}  ${MAIL_HOSTNAME}  (set via hosting provider)"
echo ""

# ========================================
# STEP 9: Restart all services
# ========================================
echo "=== Restarting services ==="
systemctl enable opendkim
systemctl restart opendkim
systemctl restart postfix
systemctl restart dovecot
echo "=== Checking services ==="
systemctl is-active opendkim postfix dovecot

echo "=== Testing Postfix config ==="
postfix check 2>&1 || true

# ========================================
# STEP 10: Test outbound delivery
# ========================================
echo "=== Testing outbound port 25 connectivity ==="
if timeout 5 bash -c 'echo QUIT | nc -w5 gmail-smtp-in.l.google.com 25' > /dev/null 2>&1; then
  echo "✅ Outbound port 25 is OPEN — direct delivery will work"
else
  echo "⚠️  Outbound port 25 appears BLOCKED"
  echo "   Your hosting provider likely blocks port 25."
  echo "   You need to either:"
  echo "   1. Request port 25 unblocking from your provider"
  echo "   2. Configure an SMTP relay (SendGrid, Mailgun, Amazon SES)"
  echo "   See the relay configuration section in README.md"
fi

echo ""
echo "=============================================="
echo "  ✅ HyveMail setup complete!"
echo "=============================================="
echo ""
echo "  CRITICAL DNS RECORDS TO ADD/VERIFY:"
echo "  ─────────────────────────────────────"
echo "  MX    @              ${MAIL_HOSTNAME} (pri 10)"
echo "  A     mail           ${SERVER_IP}"
echo "  TXT   @              v=spf1 mx a:${MAIL_HOSTNAME} ip4:${SERVER_IP} -all"
echo "  TXT   _dmarc         v=DMARC1; p=quarantine; rua=mailto:postmaster@${MAIL_DOMAIN}; fo=1"
echo "  TXT   mail._domainkey  (DKIM key printed above)"
echo "  PTR   ${SERVER_IP} → ${MAIL_HOSTNAME}  (set via hosting provider)"
echo ""
echo "  CRITICAL: Reverse DNS (PTR) record must be set"
echo "  via your hosting provider's control panel!"
echo ""
echo "  Test with: echo 'test' | mail -s 'Test' you@gmail.com"
echo "  Check logs: tail -f /var/log/mail.log"
echo "=============================================="
